baseURL = 'https://roneo.itcouldbewor.se/'
languageCode = 'en-us'
defaultContentLanguage = 'en'


[params]
  title = 'Remix, a theme for Hugo fully editable with Netlify CMS'
  metaDescription = "Hugo + Netlify CMS + One click deploy to Netlify"


# Languages
[Languages.de]
languageName = "De"
languageCode = "de-ch"
contentDir = "content/de"
weight = 1
mark = "DE"


[taxonomies]
  category= "theme"
  scene = "scenes"
